### ISSUE TITLE
SQL查询如何指定排序表达式？

### ISSUE THREAD

**Issue by breeent** [alibaba/havenask#10]
在SQL语句中进行MATCHINDEX查询或者QUERY查询的时候，请问如何对召回的文本计算文本的匹配度并按照匹配度排序呢

**Comment by breeent** [comment]
我在尝试写自己的算分逻辑的时候也遇到了一些问题，比如对于一个matchDoc，如何获取到这个matchDoc对应的数据如title等

**Comment by xuxijie** [comment]
计算文本相关性的时候需要fullmatchdata，当前版本的sql里面没有透出matchdata信息，如果需要使用文本相关性的话，可能需要使用ha3自己的dsl，具体的语法可以参考：https://help.aliyun.com/document_detail/397313.html。文本相关性插件的具体逻辑可以参考：aios/ha3/ha3/rank/DefaultScorer.cpp里面的代码。

**Comment by xuxijie** [comment]
底层的索引结构是倒排索引，可以直接获取的是查询此在doc、字段上的匹配信息，需要在算分插件中自己维护一个数据结构来还原具体的字段内容。
还有一些做法是，将title里面的分好的词进行hash，存成一个属性字段，算分的时候读取这个熟悉字段，自行计算match信息。

**Comment by breeent** [comment]
> 计算文本相关性的时候需要fullmatchdata，当前版本的sql里面没有透出matchdata信息，如果需要使用文本相关性的话，可能需要使用ha3自己的dsl，具体的语法可以参考：[https://help.aliyun.com/document_detail/397313.html。文本相关性插件的具体逻辑可以参考：aios/ha3/ha3/rank/DefaultScorer.cpp里面的代码。](https://help.aliyun.com/document_detail/397313.html%E3%80%82%E6%96%87%E6%9C%AC%E7%9B%B8%E5%85%B3%E6%80%A7%E6%8F%92%E4%BB%B6%E7%9A%84%E5%85%B7%E4%BD%93%E9%80%BB%E8%BE%91%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%EF%BC%9Aaios/ha3/ha3/rank/DefaultScorer.cpp%E9%87%8C%E9%9D%A2%E7%9A%84%E4%BB%A3%E7%A0%81%E3%80%82)

这个链接怎么打不开了呢
