### ISSUE TITLE
main版本相较于stable0.4.0性能明显下降

### ISSUE THREAD

**Issue by breeent** [alibaba/havenask#109]
用example里面的expand_dataset.py将test.data扩增到500w条，使用example里面的脚本和cases/normal里面配置，对0.4.0版本和当前版本测试

当前版本建库时间明显增加

待建库完成后拉起服务，对机器充分预热后发送请求 curl 'http://127.0.0.1:45800/?cluster=in0&&query=%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E&&config=rank_size:10000' , 0.4.0版本的耗时基本稳定在4ms，而当前版本基本稳定在25ms，查看trace发现当前版本在seek阶段耗时明显增加:
0.4.0版本：
[DEBUG ] [] [2023-07-07 20:53:18.261] [SEARCHER_in0.default_0_0_0_65535]current layer meta: [(quota: 0 maxQuota: 10000 quotaMode: 0 needAggregate: 1 quotaType: 0) begin: 0 end: 4999999 nextBegin: 0 quota: 10000;]
[DEBUG ] [] [2023-07-07 20:53:18.262] [SEARCHER_in0.default_0_0_0_65535]layer seekCount:[ 2010384 ], leftQuota:[ 0 ], matchCount:[ 10000 ], truncate ChainFactor:[ 1.000000 ],total seekCount [ 2010384 ], total matchCount [ 24870 ]

当前版本：
[DEBUG ] [] [2023-07-07 20:58:16.942] [SEARCHER_in0.default_0_0_0_65535]current layer meta: [(quota: 0 maxQuota: 10000 quotaMode: 0 needAggregate: 1 quotaType: 0) begin: 0 end: 4999999 nextBegin: 0 quota: 10000;]
[DEBUG ] [] [2023-07-07 20:58:16.959] [SEARCHER_in0.default_0_0_0_65535]layer seekCount:[ 2010384 ], leftQuota:[ 0 ], matchCount:[ 10000 ], truncate ChainFactor:[ 1.000000 ],total seekCount [ 2010384 ], total matchCount [ 24870 ]

压测也能看到cpu和吞吐都有所下降

各位大佬可以帮忙看看是什么原因吗？

**Comment by xuxijie** [comment]
你的数据是怎么构造的？直接是讲test.data里面的主键扩展到500w个吗？我们先复现一下

**Comment by xuxijie** [comment]
是不是编出来的是release版本？编译的时候加上 -c opt --copt -g --strip=never试一下

**Comment by supercocoa7654** [comment]
确实用自带的example性能也比之前要低

**Comment by xuxijie** [comment]
替换成bazel之后，默认的编译没有加上优化选项，编译的时候加上-c opt ，我们这边也将镜像更新一下

**Comment by breeent** [comment]
> 是不是编出来的是release版本？编译的时候加上 -c opt --copt -g --strip=never试一下

加上了以后性能似乎还是有差距，我把这个请求'http://127.0.0.1:45800/?cluster=in0&&query=%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E&&config=rank_size:10000'复制10000000次然后用同等压力去发压，两个版本cpu的消耗是不一样的
0.4.0版本：
![image](https://github.com/alibaba/havenask/assets/118168513/afdf4a34-5a96-4a6e-82be-04f2a1b9a28d)

当前版本：
![image](https://github.com/alibaba/havenask/assets/118168513/d790818b-8f8b-494f-a8aa-a2f3cd3949f7)

可以看到cpu idle以及进程对cpu占用差距都比较明显

数据用的是example/data/expand_dataset.py这个脚本直接扩增的，命令是 python expand_dataset.py test.data id 5000000

**Comment by xuxijie** [comment]
镜像已经更新，请用最新的1.0.0-beta2 这个版本的镜像试一下
