### ISSUE TITLE
是否支持类似es的前缀搜索(completion_suggest)

### ISSUE THREAD

**Issue by supercocoa7654** [alibaba/havenask#116]
是否支持类似es的前缀搜索(completion_suggest)，文档里没找到类似介绍，这种sql应该怎么写

**Comment by xuxijie** [comment]
不支持前缀搜索，前缀搜索主要是通过分析器来实现的，即将原始的查询词进行ngram扩展，比如 abcd，分词为a ab abc abcd，这样，查询的时候就可以做前缀匹配了
