### ISSUE TITLE
实时索引不生效

### ISSUE THREAD

**Issue by Mister-Woodpecker** [alibaba/havenask#121]
按说明文档https://github.com/alibaba/havenask/wiki/%E5%AE%9E%E6%97%B6%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3 测试实时功能未生效，log提示build/debug64/build_service/builder/BuilderMetrics.cpp -- reportMetrics():97] [unknown doc operator]

**Comment by xuxijie** [comment]
1.0.0版本的实时是借助kafka来实现的，实现了一个支持kafka的builder service reader插件，可以跟一下看看插件是否起作用。需要确认下追实时的时间是否大于数据推送的时间。
另外，可以尝试下最新版本的引擎，所有的表默认全部开启了实时功能。
