### ISSUE TITLE
构建索引时候，bad_alloc请问是为哈？步骤基本照抄

### ISSUE THREAD

**Issue by jiangtao12** [alibaba/havenask#13]
# python build_demo_data.py /ha3_install

/ha3_inst/usr/local/bin/bs startjob -c /home/root/havenask/example/scripts/../config/normal_config/offline_config/ -n in0 -j local -m full -d /home/root/havenask/example/scripts/../data/test.data -w /home/root/havenask/example/scripts/./workdir -i ./runtimedata -p 1 --documentformat=ha3
sh: /ha3_inst/usr/local/bin/bs: No such file or directory
[root@iZ2zea3idb9ewkgijwf44vZ scripts]# python build_demo_data.py /ha3_install
/ha3_install/usr/local/bin/bs startjob -c /home/root/havenask/example/scripts/../config/normal_config/offline_config/ -n in0 -j local -m full -d /home/root/havenask/example/scripts/../data/test.data -w /home/root/havenask/example/scripts/./workdir -i ./runtimedata -p 1 --documentformat=ha3
WARN: run without zookeeper lock
INFO: start build job... 
/bin/env LD_LIBRARY_PATH=/ha3_install/usr/local/lib64/:/ha3_install/usr/local/lib/:/ha3_install/usr/lib:/ha3_install/usr/lib64:/ha3_depends/usr/local/lib64:/ha3_depends/usr/local/lib:/ha3_depends/usr/lib64/:/ha3_depends/usr/lib//usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:/opt/taobao/java/jre/lib/amd64/server/:/opt/taobao/java/jre/lib/amd64/server/  HADOOP_HOME=/home/hadoop.devel/hadoop-2.6.2-cdh5.4.0-etao4/hadoop/hadoop/  JAVA_HOME=/opt/taobao/java/  VIPCLIENT_SET_FAILOVER_PATH=/tmp /ha3_install/usr/local/bin/bs_local_job  -s build -m 1 -r 1 -p '{"need_partition": "True", "merge_parallel_num": "1", "generation": "0", "service_name": "", "index_root": "./runtimedata/in0/__temp__generation_0/", "zookeeper_root": "", "document_format": "ha3", "merge_config_name": "", "map_reduce_ratio": "1", "merge_timestamp": "1670227499", "user_name": "", "cluster_names": "in0", "build_parallel_num": "1", "amon_agent_port": "10086", "partition_split_num": "1", "data": "/home/root/havenask/example/scripts/../data/test.data", "build_partition_from": "0", "partition_count": "1", "config": "/home/root/havenask/example/scripts/../config/normal_config/offline_config/0", "src_signature": "1670227499", "build_mode": "full", "build_partition_count": "1"}' 
local build failed data[] error[terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
] code[-6]

**Comment by xuxijie** [comment]
可以发下机器的配置信息吗？比如内存大小，同时看下ulimit -a看下？

**Comment by jiangtao12** [comment]
> 可以发下机器的配置信息吗？比如内存大小，同时看下ulimit -a看下？

# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3683
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655350
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1048576
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

用的阿里云的ecs云主机

**Comment by xuxijie** [comment]
只有941 M的内存吗？如果是的话这个内存太小了，最好用一个4G以上的

**Comment by dengwx2009** [comment]
可以参考下面的环境要求：
确保机器内存大于10G，cpu大于2核，磁盘大小大于50G。
使用前确保设备已经安装和启动Docker服务。
