### ISSUE TITLE
分析器demo

### ISSUE THREAD

**Issue by linyigang2022** [alibaba/havenask#143]
你好，我想问一下如何使用分析器，文档中只有三个分析器的介绍，以及一个使用jieba分词器的example，但是却没有分析器的使用文档。
在custom_analyzer中，使用jieba分词器，插入数据并使用matchIndex，可以识别出“阿里巴巴集团”是匹配“阿里巴巴”的，但是我的normal例子中，我看使用的分析器是simple_analyzer，那如果我插入一个数据“aa bb”，然后使用matchIndex查找匹配“aa”的数据，应该会有返回“aa bb”才对，为什么我这里却返回0行呢？
分析器的触发时机是在什么时候呢，每次插入数据都会触发吗？
刚开始使用havenask跑一些简单的demo，所以问题有点多，见谅==

**Comment by xuxijie** [comment]
分析器的使用在索引表结构的配置里面，对于TEXT类型的字段必须要指定分析器。插入数据时，系统会自动对TEXT类型的字段进行分词，查询时会对查询词使用索引里面字段对应的分析器进行分词，所以同一个索引下多个字段的分析器需要一样。
分词器的配置在模版里面的analyzer.json文件里面，可以check下normal case里面使用的分词器配置，simple_analyzer的分隔符，另外插入的字段是否为TEXT类型的字段

**Comment by dyuyang** [comment]
simple analyzer目前分隔符是\t，如果要在命令行输入，得用control+v+tab
这个确实不好打，我们后面改成空格，你可以先试试这种输入方法

**Comment by dyuyang** [comment]
分隔符的配置在/ha3_install/hape_conf/default/cluster_templates/havenask/direct_table/analyzer.json

**Comment by linyigang2022** [comment]
哦哦，确实有效，因为我看文档写simple_analyzer的分隔符是空格，所以有些疑惑。现在用\t作为分隔符就正常了，感谢解答！
