### ISSUE TITLE
项目系统架构是否有介绍？和 OpenSearch 上介绍的四种版本有什么区别？

### ISSUE THREAD

**Issue by PanZ12580** [alibaba/havenask#15]
另外，有本地编译启动的指引吗？

**Comment by nengshengqian** [comment]
+1

**Comment by rongjun0801** [comment]
您发来的邮件收到了，感谢！

**Comment by xuxijie** [comment]
代码编译可以参考：https://github.com/alibaba/havenask/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#%E7%BC%96%E8%AF%91%E4%BB%A3%E7%A0%81

**Comment by xuxijie** [comment]
opensearch上面的四种版本，底层的引擎都是问天引擎，在问天引擎的基础之上根据场景做了很多产品化的改造。以向量检索召回引擎为例，opensearch上的向量召回会提供一个端到端的（向量预测+向量召回）的向量检索服务，并提供友好的管控系统。但是底层的引擎核心还是问天引擎，向量检索库的核心是proxima，和开源开放出来的没有太多的差别。
