### ISSUE TITLE
Hape配置文档里服务行数，这个「服务行数」是什么意思

### ISSUE THREAD

**Issue by supercocoa** [alibaba/havenask#158]
Hape配置文档里服务行数，这个「服务行数」是什么意思
https://github.com/alibaba/havenask/blob/main/docs/havenask_docs/Hape%E9%85%8D%E7%BD%AE%E8%AF%A6%E8%A7%A3.md

还有看代码里global.conf有个allowMultiSlotInOne，这个参数又是干什么用的？

**Comment by dyuyang** [comment]
行数：也即一个数据节点有多少个replica
allowMultiSlotInOne：调度系统是否允许多个进程部署在同一台机器上，由于现在版本下所有qrs使用同一批端口，所有searcher使用同一批端口，允许多个进程部署在一台机器上可能造成端口冲突，所以这个值设置为false

**Comment by supercocoa** [comment]
「行数：一个数据节点有多少个replica」数据节点指的是searcher？那qrs查询节点qrs_hippo.json那个count/replica表示什么意思？

**Comment by dyuyang** [comment]
qrs是查询节点，searcher是数据节点
qrs由于不包含数据，所以没有分片的概念，replica就等于ip个数
searcher包含数据，需要进行分片，所以replica乘以partition分片数等于ip个数

**Comment by supercocoa** [comment]
那等于就是一张2分片表最基本的高可用就得 2副本 = 4台searcher机器，searcher_hippo.json中count=2，然后global.conf中searcherIpList包含4台searcher机器的ip，是这样配吧？ @dyuyang

**Comment by dyuyang** [comment]
对的
