### ISSUE TITLE
索引构建示例

### ISSUE THREAD

**Issue by zhenxinxu** [alibaba/havenask#164]
我看 hape 命令中 没有构建索引的示例，如何离线构建索引插入创建的表中呢

**Comment by dyuyang** [comment]
不太明白你的意思，你说的是这个hape create table命令中创建全量表命令吗
![image](https://github.com/alibaba/havenask/assets/38515034/6cc562c6-9af3-464a-9039-1e0d09e42908)

**Comment by zhenxinxu** [comment]
您好，我的意思是没看到启动 bs 的命令呀，比如我有一批原始数据，想要构建索引在传入进去，我理解您这个 -f 是已经构建好的索引全量数据传入进去的吧

**Comment by dyuyang** [comment]
hape在启动havenask的时候自动帮你启动了一个bs
-f这个参数是未构建好的原始数据，可以参考这篇文档里面-f对应的测试数据
https://github.com/alibaba/havenask/blob/main/docs/havenask_docs/Hape%E5%8D%95%E6%9C%BA%E6%A8%A1%E5%BC%8F.md

**Comment by zhenxinxu** [comment]
好的，多谢多谢，另外快速启动的那个例子里面创建表的命令，那个路径是不是没有更新呀，我看例子上是在 hape_conf 下，但实际上没有 hape_conf这层，和他平行的；
![image](https://github.com/alibaba/havenask/assets/141483427/bc5e3d41-b776-4645-8318-c5f5d95eb9f6)

**Comment by dyuyang** [comment]
确实文档有误，我们改一下
