### ISSUE TITLE
loadSearcherTarget超时失败

### ISSUE THREAD

**Issue by taomengen** [alibaba/havenask#166]
问题：
main分支使用脚本local_search_starter.py启动服务，在执行到下面的函数内部时，
ret = self.loadSearcherTarget(searcherTargetInfos, terminator.left_time())
curl返回的response["signature"]为空，导致判断条件 response["signature"] == requestSig始终无法成立，
最后loadSearcherTarget超时失败，无法进行后续的loadQrsTarget。

**Comment by dyuyang** [comment]
我这边测试好像没什么问题，能贴出你的searcher的以下文件吗
ha_sql/sql/sql.log
ha_sql/heartbeat下最新的target和current

**Comment by dyuyang** [comment]
我这边测试好像没什么问题，能贴出你的searcher工作目录下的以下文件吗
logs/sql.log
heartbeat下最新的target和current

**Comment by taomengen** [comment]
已经定位原因：启动服务阶段，加载udf 函数异常，导致load target失败，问题已经解决。
