### ISSUE TITLE
hape validate失败

### ISSUE THREAD

**Issue by goddie1** [alibaba/havenask#173]
<img width="1692" alt="image" src="https://github.com/alibaba/havenask/assets/10891462/dd3dc8a1-e303-47e9-a0a6-7c2d073aba3f">

**Comment by dyuyang** [comment]
子命令支持-v选项，可以看到详细执行过程，看看是哪一步failed了

**Comment by goddie1** [comment]
<img width="1749" alt="image" src="https://github.com/alibaba/havenask/assets/10891462/1e646967-489a-42c4-ae8f-843d2b98e059">
看着是权限问题？要ls的这个目录是存在的

**Comment by dyuyang** [comment]
当前账号在home下没权限吗？

**Comment by goddie1** [comment]
肯定有的

**Comment by goddie1** [comment]
代码都在这个目录，我手动执行ls命令是可以的，执行mkdir提示目录已经存在

**Comment by dyuyang** [comment]
手动执行的时候有带上提示里面的ssh那一堆前缀吗

**Comment by goddie1** [comment]
没有，带上了以后确实不行。

**Comment by dyuyang** [comment]
按照上面的提示执行ssh免密登录，去掉后面执行的命令
ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no  <你的ip>

登录上去以后手动执行那些命令，看看为啥没权限？

**Comment by goddie1** [comment]
登陆上去以后，home目录变成/export/home/xxx，没有/home/xxx目录，创建也不行。

**Comment by goddie1** [comment]
手动创建了目录/home/xxx，解决了问题

**Comment by goddie1** [comment]
感谢

**Comment by dyuyang** [comment]
为啥会是export

**Comment by goddie1** [comment]
应该是我自己设置的原因，/home目录的资源有限，我创建用户的时候会把home目录指定到export下
