### ISSUE TITLE
执行demo创建表in1报错

### ISSUE THREAD

**Issue by goddie1** [alibaba/havenask#174]
执行hape start havenask已经成功，
再执行demo：
hape create table -t in1 -p 1 -s /ha3_install/example/cases/normal/in0_schema.json  -f /ha3_install/example/data/test.data  -v，
报错：

[2023-10-27 17:27:03,843] [INFO] [swift.py:_try_add_topic:151]: Get swift topic status Response: admin leader: tcp:xxx.xxx.xxx.xxx:58383
TopicName: in1
TopicMode: security_mode
MaxCommitTime: 50000
MaxCommitSize: 1048576
NeedFieldFilter: false
NeedSchema: false
SchemaVersions:
TopicStatus: WAITING
PartitionCount: 1
RangeCountInPartition: 1
PartitionMaxBufferSize: 1024
PartitionMinBufferSize: 8
PartitionBufferSize: 0
PartitionFileBufferSize: 0
PartitionResource: 30
PartitionLimit: 100000
ObsoleteFileTimeInterval: -1
ReservedFileCount: -1
DeleteTopicData: false
TopicGroup: default
TopicExpiredTime: -1
owners: NONE
TopicType: TOPIC_TYPE_NORMAL
physicTopicLst: []
Sealed: false
enableTTLDel: true
readSizeLimitSec: -1
enableLongPolling: false
versionControl: false
enableMergeData: false
permitUser: NONE
readNotCommittedMsg: true
Partition(waiting/starting/running/stopping/recovering/none): 1/0/0/0/0/0

[2023-10-27 17:27:03,845] [INFO] [swift.py:_try_add_topic:152]: Swift Topic status is not ready
[2023-10-27 17:27:03,846] [INFO] [retry.py:retry:11]: Check [swift topic created and ready] not succeed by now, retry 19/20, wait up to 100 seconds
[2023-10-27 17:27:08,853] [WARNING] [retry.py:retry:16]: Check [swift topic created and ready] timeout
[2023-10-27 17:27:08,854] [ERROR] [hape_cluster.py:create_table:136]: Add swift topic failed

**Comment by dyuyang** [comment]
能否参考这个提供一下home下面的swift日志？以及docker ps| grep swift看一下swift容器是否创建成功？https://github.com/alibaba/havenask/blob/main/docs/havenask_docs/Hape%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E4%B8%8E%E6%8E%92%E6%9F%A5.md

**Comment by goddie1** [comment]
1. docker ps |grep swift 结果：
02dd366fff5a   registry.cn-hangzhou.aliyuncs.com/havenask/ha3_runtime:1.0.0    "/sbin/init"   About an hour ago   Up About an hour             havenask-swift-local_appmaster
看着这个没起来。

**Comment by dyuyang** [comment]
看起来就是swift admin异常，在工作目录的swift.log看看有无ERROR，或者贴在这个issue里面我们看看

**Comment by goddie1** [comment]
没找到swift.log日志，我早上重新刷了下环境，把havenask安装在/home/user目录下，问题都解决了，看起来对安装目录有强依赖。
