### ISSUE TITLE
单机模式下swift的broker 启动不成功

### ISSUE THREAD

**Issue by zhenxinxu** [alibaba/havenask#182]
我按照文档启动了havenask， 配置了ssh免密，启动后查看swift 发现swift 的broker 启动不成功，

**Comment by zhenxinxu** [comment]
[swift.log](https://github.com/alibaba/havenask/files/13225030/swift.log)
[Uploading hippo.log…]()

**Comment by zhenxinxu** [comment]
我看这个swift 这个目录下的stderr 的日志，一直说无法在Could not create directory '/export/xuzhenxin5/.ssh' 但是事实上这个目录已经存在了

**Comment by dyuyang** [comment]
root账号换了普通账号还是不行？

**Comment by zhenxinxu** [comment]
嗯，切换了我自己的账户，也不行
[hippo.log](https://github.com/alibaba/havenask/files/13225086/hippo.log)

**Comment by dyuyang** [comment]
为什么是/export/xuzhengxin5目录，之前也有个用户用的/export目录失败的
https://github.com/alibaba/havenask/issues/173

**Comment by zhenxinxu** [comment]
.ssh 目录是在/export/xuzhenxin5下，因为机器的家目录挂载了/export下

**Comment by zhenxinxu** [comment]
havenask 的三个文件夹是在/home/<user>/下

**Comment by zhenxinxu** [comment]
那就是必须在/home/目录下吗？

**Comment by dyuyang** [comment]
估计还是hape目前在调度上不完善，导致路径处理上有问题。目前最稳定的做法就是在/home/\<user\>目录下
如果不方便在这种目录下运行，参考一下这个issue，看看执行hape validate命令能否成功，不能成功的话和他一样手动建一下目录
https://github.com/alibaba/havenask/issues/173

![image](https://github.com/alibaba/havenask/assets/38515034/bfa14c1f-b553-4856-aa57-55577f699455)

**Comment by zhenxinxu** [comment]
我也手动创建了，是有的，hape validate命令也是可以执行成功的

**Comment by zhenxinxu** [comment]
我和他的问题不是一样的，我本身是有/home/xxx这个目录的，三个havenask的文件夹是在/home/xxx目录下，只不过.ssh的秘钥是在/export/xxx/ 下

**Comment by dyuyang** [comment]
手动执行hippo.log里面报错的这个命令看看返回什么
ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no 127.0.0.1 'docker run --volume="/etc/hosts:/etc/hosts:ro" --ulimit nofile=655350:655350  --ulimit memlock=-1 --ulimit core=-1 --network=host --privileged -d  --cpu-quota=500000 --cpu-period=100000 --memory=10240m -v /home/xuzhenxin5:/home/xuzhenxin5 -v /etc/passwd:/home/.passwd -v /etc/group:/home/.group --name havenask_container_xuzhenxin5_havenask-swift-local_0 registry.cn-hangzhou.aliyuncs.com/havenask/ha3_runtime:1.0.0 /sbin/init 2>&1'

**Comment by dyuyang** [comment]
如果没有报错看看容器是否正常运行
docker ps --all | grep havenask_container_xuzhenxin5_havenask-swift-local_0

**Comment by dyuyang** [comment]
> 我和他的问题不是一样的，我本身是有/home/xxx这个目录的，三个havenask的文件夹是在/home/xxx目录下，只不过.ssh的秘钥是在/export/xxx/ 下

/home/xxx/下能访问到.ssh秘钥吗

**Comment by zhenxinxu** [comment]
手动执行这条命令是没问题的，容器运行，进程没起来

**Comment by zhenxinxu** [comment]
可以访问啊，在这个目录下直接ssh 可以免密登录呀

**Comment by dyuyang** [comment]
@WenyiDuan 看一下这个，swift admin的hippo.log显示broker容器启动不起来，但是手动执行对应docker命令能启动容器

**Comment by zhenxinxu** [comment]
![image](https://github.com/alibaba/havenask/assets/141483427/0bbc4b4a-10b9-4306-ae87-d3c4c7f5f1c1)
嗯，手动能启动，但是hape start havenask的时候这个容器起不来，但是日志里面显示退出码也是0

**Comment by WenyiDuan** [comment]
你手动启动后，通过ssh去check容器是否启动`ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no 127.0.0.1 'docker ps |grep havenask_container_xuzhenxin5_havenask-swift-local_0 2>&1'`，返回结果是对的吗？

**Comment by zhenxinxu** [comment]
![image](https://github.com/alibaba/havenask/assets/141483427/2884e0fa-4fd6-48c3-aefb-f3b452442b80)
是对的

**Comment by zhenxinxu** [comment]
换了台机器，用/home/xx 单机模式已经搭建起来了，多谢大家了
