### ISSUE TITLE
支持一些基本的打分排序能力

### ISSUE THREAD

**Issue by ARSwhut** [alibaba/havenask#193]
目前文本相关性这块的打分排序需要业务写udf实现，这块的例子和单测比较少，可以考虑增加一些使用demo

**Comment by xuxijie** [comment]
下个版本会增加一个内置的bm25的udf，到时候可以使用下

**Comment by xuxijie** [comment]
最新的1.1.0 版本已经支持了一些基础的udf，你可以看下
