### ISSUE TITLE
统一文档中schema配置

### ISSUE THREAD

**Issue by ARSwhut** [alibaba/havenask#208]
倒排索引配置说明.md: https://github.com/alibaba/havenask/blob/main/docs/havenask_docs/%E5%80%92%E6%8E%92%E7%B4%A2%E5%BC%95%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E.md
和schema配置.md: https://github.com/alibaba/havenask/blob/main/docs/havenask_docs/schema%E9%85%8D%E7%BD%AE.md
这两个文档中schema配置不统一，可以帮忙更新下文档，统一schema配置格式

**Comment by dyuyang** [comment]
已统一
