### ISSUE TITLE
编译时总是报这个错，OfflineConfigBase size change

### ISSUE THREAD

**Issue by eyun221** [alibaba/havenask#21]
看了下，在这个文件中 aios/indexlib/indexlib/config/offline_config.h
这个size为啥会变啊？

class OfflineConfig : public OfflineConfigBase
{
    static_assert(sizeof(OfflineConfigBase) == 312, "OfflineConfigBase size change!");

**Comment by foreverhy** [comment]
有具体的编译报错信息吗，是修改了 OfflineConfigBase.h 文件么？

**Comment by eyun221** [comment]
> 有具体的编译报错信息吗，是修改了 OfflineConfigBase.h 文件么？

没有修改。我是把docker里面的ha3_deps文件copy到linux机器上编译的，注释掉这个static assert可以编译过

**Comment by foreverhy** [comment]
有具体的编译报错信息吗，包括编译器版本

**Comment by eyun221** [comment]
gcc 8.3.0, 
bazel-out/k8-fastbuild/bin/_virtual_includes/indexlib/indexlib/config/offline_config.h:17:45: error: static assertion failed: OfflineConfigBase size change!
     static_assert(sizeof(OfflineConfigBase) == 312, "OfflineConfigBase size change!");

**Comment by eyun221** [comment]
编译参数大概是这样
/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/_objs/indexlib/patch_modifier.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/_objs/indexlib/patch_modifier.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/genfiles -iquote bazel-out/k8-fastbuild/bin -Ibazel-out/k8-fastbuild/bin/_virtual_includes/indexlib -Ibazel-out/k8-fastbuild/bin/_virtual_includes/alib '-std=c++14' -msse4.2 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c aios/indexlib/indexlib/partition/modifier/patch_modifier.cpp -o bazel-out/k8-fastbuild/bin/_objs/indexlib/patch_modifier.pic.o

**Comment by foreverhy** [comment]
编译选项中没有 -D_GLIBCXX_USE_CXX11_ABI=0 吗

**Comment by eyun221** [comment]
> 编译选项中没有 -D_GLIBCXX_USE_CXX11_ABI=0 吗

没有，我试一下

**Comment by eyun221** [comment]
> _GLIBCXX_USE_CXX11_ABI=0

加了以后可以了，万分感谢
