### ISSUE TITLE
QUERY 中缺少NOT 查询条件，只有ANDNOT

### ISSUE THREAD

**Issue by ARSwhut** [alibaba/havenask#221]
我们需求A=a OR (B!=b) RANK C=c 转换下就是 A:a OR ANDNOT B=b RANK C:c，试了下OR和ANDNOT 是不支持的，只能一部分写在原生sql，一部分写在QUERY里面，而且ANDNOT和RANK 都需要前置条件，如果我们只是想要QUERY(ANDNOT | RANK A) 就不支持，我们这个需求想问问有什么好的建议吗？

**Comment by ARSwhut** [comment]
或者可以转换为如何直接使用RANK，A:a OR ANDNOT B=b可以直接用 (contain(A, 'a') OR (NOT contain(B, 'b'))) AND QUERY(RANK C:c)，但是RANK使用需要前置条件，不能直接使用

**Comment by xuxijie** [comment]
RANK是不影响召回的，只是在计算文本分的时候起作用，如果你的数据量不大的话，可以搞一个每个文档内容都一致的字段，然后用它ANDNOT B，但是文档量比大的话会比较好使

**Comment by ARSwhut** [comment]
> RANK是不影响召回的，只是在计算文本分的时候起作用，如果你的数据量不大的话，可以搞一个每个文档内容都一致的字段，然后用它ANDNOT B，但是文档量比大的话会比较好使

我们全量doc 差不多 3-4亿左右

**Comment by xuxijie** [comment]
RANK C想达到什么作用？

**Comment by xuxijie** [comment]
C是一个分词的字段吗？

**Comment by CGM397** [comment]
> C是一个分词的字段吗？

string text 都有，string的话就是对匹配上的一个word打分，text就是对匹配上的一个term打分

**Comment by ARSwhut** [comment]
@xuxijie 大佬可以帮忙看看除了加一个额外的字段还有其他的解决方案吗？
