### ISSUE TITLE
[issue] contain能召回而QUERY不能召回case

### ISSUE THREAD

**Issue by ARSwhut** [alibaba/havenask#226]
contain:
{\"assemblyQuery\": \"select attr_item_id,attr_product_ne_tag_v2 from item_global_id_normal_20231207_000000 where contain(attr_behavior_feature,'C_dinda dress') limit 2500&&kvpair=databaseName:database;formatType:string;trace:INFO\"}
QUERY:
{\"assemblyQuery\": \"select attr_item_id, attr_shop_id from item_global_id_normal_20231207_000000 where QUERY('', 'attr_behavior_feature : \\\"C_dinda dress\\\"') limit 2500&&kvpair=databaseName:database;formatType:string;trace:INFO\"}

schema:
{
            "name": "attr_behavior_feature",
            "type": "TEXT",
            "analyzer": "rank_feature_analyzer"
        },
{
          "name": "attr_behavior_feature",
          "index_config": {
              "index_params": {
                  "term_payload_flag": "1",
                  "doc_payload_flag": "1",
                  "position_payload_flag": "0",
                  "position_list_flag": "0",
                  "term_frequency_flag": "0"
              },
              "index_fields": [
                  {
                      "field_name": "attr_behavior_feature"
                  }
              ]
          },
          "index_type": "TEXT"
},
rank_feature_analyzer 是自定义的分词器，用来分词text+payload的

trace log:
[contain.log](https://github.com/alibaba/havenask/files/13655136/contain.log)
[query.log](https://github.com/alibaba/havenask/files/13655142/query.log)

分析:
query.log中初始化失败：
[7b38e50b-226-149f4c3d] [2023-12-12 22:28:53.129570] [TRACE1] [144055,aios/sql/ops/scan/scan_visitor/ScanIteratorCreatorR.cpp -- createQueryExecutors(0x100f8c6be0):731] [node graph 1 normal_scan_r@kernel_0 kernel navi.r_create] [table name [item_global_id_normal_20231207_000000], empty result scan condition. query [TermQuery$1:[Term:[attr_behavior_feature||c_dinda dress|100|]]]] []
[7b38e50b-226-149f4c3d] [2023-12-12 22:28:53.129571] [TRACE1] [144055,aios/sql/ops/scan/scan_visitor/ScanIteratorCreatorR.cpp -- createHa3ScanIterator(0x100f8c6be0):641] [node graph 1 normal_scan_r@kernel_0 kernel navi.r_create] [create query executors failed] []
[7b38e50b-226-149f4c3d] [2023-12-12 22:28:53.129573] [TRACE3] [144055,aios/sql/ops/scan/NormalScanR.cpp -- init(0x100f8c6be0):175] [node graph 1 normal_scan_r@kernel_0 kernel navi.r_create] [after create scan iterator[(nil)] type[]] []

@xuxijie @dyuyang 大佬们能帮忙看看吗？

**Comment by xuxijie** [comment]
schema和analyzer.json 贴下

**Comment by xuxijie** [comment]
analzer的配置贴下

**Comment by xuxijie** [comment]
c_dinda dress 这个是期望不分词的吗？我看日志上分词之后还是它

**Comment by ARSwhut** [comment]
> c_dinda dress 这个是期望不分词的吗？我看日志上分词之后还是它
[analyzer.json](https://github.com/alibaba/havenask/files/13655275/analyzer.json)

@xuxijie 
attr_behavior_feature 这个字段的数据是 c_dinda dress^A0.25^Bc_dinna apple^A 其中先^B 分词，然后在自定义documentProcessor 里面^A 分词成token: c_dinda dress，docpayload: 0.25，

**Comment by xuxijie** [comment]
你可以确认建索引的词是c_dinda dress这个而不是c_dinda dress^A0.25 这个吗？

**Comment by ARSwhut** [comment]
> 你可以确认建索引的词是c_dinda dress这个而不是c_dinda dress^A0.25 这个吗？

@xuxijie 确认，可以用 attr_behavior_feature=c_dinda dress 或者 contain(attr_behavior_feature,'C_dinda dress') 召回，而且用自定义的udf 也可以打分，只是QUERY('', 'attr_behavior_feature : \"C_dinda dress\"') 召回不了

**Comment by ARSwhut** [comment]
attr_behavior_feature 这个字段是用来打分的，可匹配也可不匹配，需要用到QUERY 中的RANK，所以只能写在QUERY 里面

**Comment by xuxijie** [comment]
你把你的documentProcessor逻辑贴下，主要就是重新生成token那块

**Comment by ARSwhut** [comment]
> 你把你的documentProcessor逻辑贴下，主要就是重新生成token那块

@xuxijie 
        static const char TERM_PAYLOAD_SEPARATOR = '\x01';
        // set text term payload
        auto texts = autil::StringUtil::split(text, TERM_PAYLOAD_SEPARATOR);
        if (texts.size() == 2) {
            float termDocWeight = 0.0;
            if (!autil::StringUtil::strToFloat(texts[1].c_str(), termDocWeight)) {
                std::stringstream ss;
                ss << "cast term doc weight failed, [" << texts[1] << "]";
                std::string errorMsg = ss.str();
                AUTIL_LOG(WARN, "%s", errorMsg.c_str());
                return false;
            }
            indexlib::config::PayloadConfig payloadConfig;
            docpayload_t docPayload = fp16_ieee_from_fp32_value(termDocWeight);
            AUTIL_LOG(DEBUG, "RankFeature termDocWeight is [%f], docPayload is [%d], term is [%s]", termDocWeight, docPayload, texts[0].c_str());
            classifiedDocument->setTermDocPayload(payloadConfig, texts[0], docPayload);
            token.setText(texts[0]);
            token.setNormalizedText(texts[0]);
        }

**Comment by xuxijie** [comment]
token 这个变量从哪来的？

**Comment by ARSwhut** [comment]
> token

@xuxijie 参照TokenizeDocumentProcessor 拿到的
indexlib::document::AnalyzerToken token;

    while (analyzer->next(token)) {
        const std::string& text = token.getText();
        assert(text.length() > 0);
        if (text[0] == SECTION_WEIGHT_SEPARATOR) {
            if (ExtractSectionWeight(section, *analyzer)) {
                section = nullptr;
                continue;
            } else {
                break;
            }
        }
...
就是按^B 分词后的结果，c_dinda dress^A0.25和c_dinna apple^A0.1

**Comment by xuxijie** [comment]
没有看懂？你要不全贴一下？

**Comment by ARSwhut** [comment]
> 没有看懂？你要不全贴一下？

bool TokenizeClassifiedDocumentConvertor::DoTokenizeTextField(const indexlib::document::TokenizeFieldPtr& field,
                                                    const autil::StringView& fieldValue, Analyzer* analyzer,
                                                    const indexlibv2::document::ClassifiedDocumentPtr& classifiedDocument)
{
    indexlib::document::TokenizeSection* section = nullptr;
    indexlib::document::TokenizeSection::Iterator iterator;
    analyzer->tokenize(fieldValue.data(), fieldValue.size());

    indexlib::document::AnalyzerToken token;

    while (analyzer->next(token)) {
        const std::string& text = token.getText();
        assert(text.length() > 0);
        if (text[0] == SECTION_WEIGHT_SEPARATOR) {
            if (ExtractSectionWeight(section, *analyzer)) {
                section = nullptr;
                continue;
            } else {
                break;
            }
        }
        if (text[0] == MULTI_VALUE_SEPARATOR && !token.isDelimiter()) {
            section = nullptr;
            continue;
        }

        if (section == nullptr) {
            section = field->getNewSection();
            if (nullptr == section) {
                std::stringstream ss;
                ss << "Create section failed, fieldId = [" << field->getFieldId() << "]";
                std::string errorMsg = ss.str();
                AUTIL_LOG(ERROR, "%s", errorMsg.c_str());
                return false;
            }
            iterator = section->createIterator();
        }

        // set text term payload
        auto texts = autil::StringUtil::split(text, TERM_PAYLOAD_SEPARATOR);
        if (texts.size() == 2) {
            float termDocWeight = 0.0;
            if (!autil::StringUtil::strToFloat(texts[1].c_str(), termDocWeight)) {
                std::stringstream ss;
                ss << "cast term doc weight failed, [" << texts[1] << "]";
                std::string errorMsg = ss.str();
                AUTIL_LOG(WARN, "%s", errorMsg.c_str());
                return false;
            }
            indexlib::config::PayloadConfig payloadConfig;
            docpayload_t docPayload = fp16_ieee_from_fp32_value(termDocWeight);
            AUTIL_LOG(DEBUG, "RankFeature termDocWeight is [%f], docPayload is [%d], term is [%s]", termDocWeight, docPayload, texts[0].c_str());
            classifiedDocument->setTermDocPayload(payloadConfig, texts[0], docPayload);
            token.setText(texts[0]);
            token.setNormalizedText(texts[0]);
        }

        if (token.isBasicRetrieve()) {
            section->insertBasicToken(token, iterator);
        } else {
            section->insertExtendToken(token, iterator);
        }
    }
    return true;
}

**Comment by xuxijie** [comment]
你看下searcher的日志，有没有说为什么创建queryExecutor失败，是不是默认索引名没填？

**Comment by ARSwhut** [comment]
> 你看下searcher的日志，有没有说为什么创建queryExecutor失败，是不是默认索引名没填？

@xuxijie searcher 里面没有相关的log

**Comment by xuxijie** [comment]
![image](https://github.com/alibaba/havenask/assets/115977247/68cf5776-6938-4185-be20-d047ff9426cb)
看你的query trace，是一个empty scan，这个意思就是查询词没有结果。就是查询词没有建索引

**Comment by ARSwhut** [comment]
> ![image](https://private-user-images.githubusercontent.com/115977247/290067052-68cf5776-6938-4185-be20-d047ff9426cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Mzg5MjUsIm5iZiI6MTcwMjQzODYyNSwicGF0aCI6Ii8xMTU5NzcyNDcvMjkwMDY3MDUyLTY4Y2Y1Nzc2LTY5MzgtNDE4NS1iZTIwLWQwNDdmZjk0MjZjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMzM3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzc5M2JhMDJjMDM1YmNlYTAyOWY5ODY1YTVhMTRkNmI2ZTAwOWRlNzYxMTk5YzE5NWI0OGVhODViNjkyZmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fPM4wMABHk2k7pl_OzbasPlIkshArBH1Dav1nCLqWzc) 看你的query trace，是一个empty scan，这个意思就是查询词没有结果。就是查询词没有建索引

如果没有建索引的话，contain 也应该差不到结果吧？现在是contain 能查到，但是QUERY 查不到

**Comment by xuxijie** [comment]
是不是大小写的问题，contain是没有做归一化的，分词是做了归一化的

**Comment by ARSwhut** [comment]
> 是不是大小写的问题，contain是没有做归一化的，分词是做了归一化的，上下两个termQuery里面的内容只有大小写不一样了

@xuxijie 刚刚试了下QUERY 里面大写改成小写也不行
[924ded6d-27-4aa1061c] [2023-12-13 11:47:21.231219] [TRACE1] [381233,aios/sql/ops/scan/scan_visitor/ScanIteratorCreatorR.cpp -- createQueryExecutors(0x103ef46be0):731] [node graph 1 normal_scan_r@kernel_0 kernel navi.r_create] [table name [item_global_id_normal_20231212_000000], empty result scan condition. query [TermQuery$1:[Term:[attr_behavior_feature||c_dinda dress|100|]]]] []
[924ded6d-27-4aa1061c] [2023-12-13 11:47:21.231220] [TRACE1] [381233,aios/sql/ops/scan/scan_visitor/ScanIteratorCreatorR.cpp -- createHa3ScanIterator(0x103ef46be0):641] [node graph 1 normal_scan_r@kernel_0 kernel navi.r_create] [create query executors failed] []

**Comment by xuxijie** [comment]
现在query里面修改已经没有用了，query总是会转成小写的，就是你建索引的时候设置的token是大写的还是小写的？

**Comment by xuxijie** [comment]
你的text应该取的是normalized text，而不是text。但是上面你给出来的文档的内容都是小写的，这个有点奇怪

**Comment by ARSwhut** [comment]
> 现在query里面修改已经没有用了，query总是会转成小写的，就是你建索引的时候设置的token是大写的还是小写的？
测试了下是大小写问题，建索引的时候设置的token是大写没有处理成小写，在QUERY的时候变成小写了，所以不匹配查不到

**Comment by ARSwhut** [comment]
@xuxijie 可以在documentProcessor里面成小写，问题已解决，感谢

**Comment by xuxijie** [comment]
好的
