### ISSUE TITLE
Havenask支持分布式部署

### ISSUE THREAD

**Issue by xuxijie** [alibaba/havenask#24]
目前，Havenask还是单机版本，希望可以支持分布式版本，支持多分片，多replica部署。

**Comment by dyuyang** [comment]
### havenask分布式工具hape
开发中功能

- [ ] 启停集群
- [ ] 构建索引
- [ ] searcher加载索引、挂载qrs
- [ ] 分发和加载配置
- [ ] 集群状态透出

**Comment by dyuyang** [comment]
> ### havenask分布式工具hape
> 开发中功能
> 
> * [x]  启停集群
> * [x]  构建索引
> * [x]  searcher加载索引、挂载qrs
> * [x]  分发和加载配置
> * [x]  集群状态透出

[PR #40 ](https://github.com/alibaba/havenask/pull/40)
