### ISSUE TITLE
swift c++ client希望能尽快开放

### ISSUE THREAD

**Issue by breeent** [alibaba/havenask#242]
实际使用swift的python写入工具发现这个工具耗时较高，性能较差，难以大规模使用。希望大佬们可以早点把c++的客户端开源出来。
而且看实现swift用的应该是arpc，相关文档较少，我们自己开发一个go的客户端比较困难，能否也支持一下go的客户端呢？

**Comment by xuxijie** [comment]
https://github.com/alibaba/havenask/tree/main/aios/apps/facility/swift/client
swift的c++ client已经开出来了

**Comment by xuxijie** [comment]
java的客户端最近也会开放出来，go的客户端短期内无法支持

**Comment by breeent** [comment]
了解，感谢回复。
