### ISSUE TITLE
suez_admin_worker疑似存在内存泄漏

### ISSUE THREAD

**Issue by breeent** [alibaba/havenask#250]
用 镜像ha3_runtime:1.1.1 在两台机器上拉起服务并创建一个全量表，其中 global.conf 中的 [havenask] 配置有 adminMem=20480

观察到的现象是 ps -o rss <suez_admin_worker pid> 持续增加，过了一段时间suez_admin_worker挂掉，在stderr.log最后有
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
  
1.各位大佬们能否排查一下是否存在内存泄漏的问题
2.suez_admin_worker挂掉后有什么办法能重新拉起admin

**Comment by xuxijie** [comment]
你看下https://github.com/alibaba/havenask/pull/245 这个pr，是不是已经解决了

**Comment by breeent** [comment]
> 你看下#245 这个pr，是不是已经解决了

拿最新的代码编译跑了一下，目前看内存的增加已经很少了👍

再请教一个问题就是，如果suez_admin_worker挂了有什么方法可以在不影响在线服务的情况下重新拉起来吗

**Comment by xuxijie** [comment]
你看下最新的代码，一定程度上修复了这个问题
