### ISSUE TITLE
关于 disable_follower_build 的问题

### ISSUE THREAD

**Issue by breeent** [alibaba/havenask#251]
在hape_conf里面的offline_table/clusters/default_cluster.json有配置项 `"disable_follower_build":
    true`
在全量表模式下，成为leader的searcher会消费实时数据，成为follower的searcher不会消费实时数据，导致实时写入的doc有时能查到，有时查不到。

请教一下这个选项一般是使用在什么场景呢？默认为false是否合理一些。

**Comment by xuxijie** [comment]
是的，这个参数对于直写表有意义，对于全量表，这个参数应该设置为false
