### ISSUE TITLE
执行 创建直写表的命令失败（hape create table -t in0 -p 1 -s /ha3_install/example/cases/normal/in0_schema.json）

### ISSUE THREAD

**Issue by XuLei1992** [alibaba/havenask#256]
![Uploading QQ截图20240403110725.png…]()

**Comment by XuLei1992** [comment]
![QQ截图20240403110725](https://github.com/alibaba/havenask/assets/46668711/230569fe-7f53-429d-b287-7bacbad47a26)

**Comment by XuLei1992** [comment]
![image](https://github.com/alibaba/havenask/assets/46668711/08a60919-9128-4d1c-8fc6-defe810ab702)

**Comment by dyuyang** [comment]
参考这个看一下database这个节点的日志sql.log有没有明显ERROR
https://havenask.net/#/doc/v1-1-0/sql/petool/problem#%E5%BC%95%E6%93%8E%E6%97%A5%E5%BF%97%E6%8E%92%E6%9F%A5%E6%96%B9%E6%B3%95

**Comment by XuLei1992** [comment]
![image](https://github.com/alibaba/havenask/assets/46668711/9c27903e-d50b-4667-b4ef-4db74227fcca)
sql.log中提示端口被占用，但是没有
