### ISSUE TITLE
Havenask支持业务插件开发，并提供相关文档

### ISSUE THREAD

**Issue by xuxijie** [alibaba/havenask#26]
Havenask支持分析器插件、数据处理插件、query改写插件、function功能插件、算分插件、摘要插件的开发，并提供demo实现和开发文档。

**Comment by lixuefeng123** [comment]
function功能插件PR [#28 ]

**Comment by lixuefeng123** [comment]
数据处理插件和摘要插件PR[#36 ](https://github.com/alibaba/havenask/pull/36)
