### ISSUE TITLE
单机版部署报错

### ISSUE THREAD

**Issue by littledoglily** [alibaba/havenask#266]
复现步骤：
1、root登陆，添加个人账户maximeli，并指定userid
2、通过scp 把havenask tag=1.2.0的包传到ecs机器，路径/home/maximeli下(未采用git clone方式 因为GitHub网络不通)
3、解压包路径为havenask-1.2.0,  拉取镜像 registry.cn-hangzhou.aliyuncs.com/havenask/ha3_runtime:latest
4、执行./create_container.sh <CONTAINER_NAME> registry.cn-hangzhou.aliyuncs.com/havenask/ha3_runtime:latest
5、配置免密登陆，因为hostname -i为多个ip， 所以手动选择ip 执行ssh-copy-id -i ~/.ssh/id_rsa maximeli@
6、执行./<CONTAINER_NAME>/sshme
7、进容器之后执行 hape validate，报错如下：
![image](https://github.com/alibaba/havenask/assets/34212554/72c62c1b-f72e-477f-b83f-3660ac500a72)

**Comment by dyuyang** [comment]
登录这台机器docker images看看有吗

**Comment by littledoglily** [comment]
> 登录这台机器docker images看看有吗

是有的，按照文档拉取的是lastest的版本，但是我看create_container.sh里面是固定1.2.0的版本，跟这个有关系吗？
PS：可否在视频中把一些步骤操作的详细一点，单机版那个视频账户创建、公钥都是之前环境配置好的
![image](https://github.com/alibaba/havenask/assets/34212554/84ebcea7-1a9b-4116-b7d9-13040f736694)

**Comment by dyuyang** [comment]
validate的失败之前有个DEBUG日志，显示了当前执行什么命令，手动执行看看是否有结果？

**Comment by dyuyang** [comment]
应该是1.2.0不存在，只有lattest导致的，你可以手动docker tag为1.2.0试试看，这个问题我们改一下

**Comment by littledoglily** [comment]
> 登录这台机器docker images看看有吗

有的，因为文档中是拉取lastest版本，但是create_container.sh里面是写的1.2.0的版本

> 应该是1.2.0不存在，只有lattest导致的，你可以手动docker tag为1.2.0试试看，这个问题我们改一下



> 应该是1.2.0不存在，只有lattest导致的，你可以手动docker tag为1.2.0试试看，这个问题我们改一下

手动把tag改成1.2.0 可以了
