### ISSUE TITLE
在执行sshme的时候出现错误

### ISSUE THREAD

**Issue by txdy001** [alibaba/havenask#267]
![image](https://github.com/alibaba/havenask/assets/80944998/e800334a-0058-447b-94cb-bb9263c6297e)

**Comment by txdy001** [comment]
有没有人遇到这个问题啊

**Comment by txdy001** [comment]
> 按照说明通过脚本创建容器的时候有报错吗

这个没有出错，我在想是不是跟那个ssh免密登录有关，后面改了一大堆，包括重装了ubuntu虚拟机，但是执行那个sshme的时候还是会出现上述问题

**Comment by dyuyang** [comment]
为啥是在root下执行

**Comment by txdy001** [comment]
> 为啥是在root下执行

不在root下命令直接会报错

**Comment by dyuyang** [comment]
不在root下是报docker的错吗

**Comment by txdy001** [comment]
> 不在root下是报docker的错吗

![image](https://github.com/alibaba/havenask/assets/80944998/55a1bc67-e544-4138-910c-e3391e2f2b48)
甚至docker都没法启动

**Comment by dyuyang** [comment]
在对应机器上执行sudo chmod 666 /var/run/docker.sock试试看
https://havenask.net/#/doc/v1-2-0/sql/petool/problem#%E5%88%9B%E5%BB%BA%E8%BF%9B%E7%A8%8B%E4%B8%8D%E6%88%90%E5%8A%9F

**Comment by txdy001** [comment]
> 在对应机器上执行sudo chmod 666 /var/run/docker.sock试试看 https://havenask.net/#/doc/v1-2-0/sql/petool/problem#%E5%88%9B%E5%BB%BA%E8%BF%9B%E7%A8%8B%E4%B8%8D%E6%88%90%E5%8A%9F

好的好的，我看到了，谢谢你的回答好兄弟，我尝试一下，我原打开过sshme文件，想过这个问题，发现用户就是dong，可能确实不能在root下执行
