### ISSUE TITLE
希望qrs开启SO_REUSEPORT选项

### ISSUE THREAD

**Issue by troycheng** [alibaba/havenask#27]
目前部署使用的是大规格裸金属机器，核数在96,104到256不等，部署上需要单机多实例并绑定numa节点。为了对上游屏蔽具体机型差异，结合现有服务发现机制现状，最好方式是服务对外提供统一端口号，可选的实现方式有两种：

1. 通过k8s虚拟网络方式（非HOST网络）完成内外端口映射
2. 使用HOST网络并在进程监听端口时开启[SO_REUSEPORT](https://man7.org/linux/man-pages/man7/socket.7.html)选项，支持单机多实例复用端口

对于第1种方式，在非极端压力场景下足够使用，但在时延敏感/网络传输压力大的场景下，K8s虚拟网络存在时延损失以及容易出现各种概率性的超时问题。

因此当前生产环境选用的是方案2，当前qrs所用sap_server未开放代码，希望开放代码或者能够支持SO_REUSEPORT选项，非常感谢

**Comment by xuxijie** [comment]
第一个方案使用的是阿里云的弹性网卡吗？就是一个机器上可以挂载多个网卡，每个网卡有独立的ip地址，启动容器时指定对应的ip地址。

**Comment by troycheng** [comment]
不是的，第一种可以理解就是走k8s内部svc方式，它的问题主要在于，对耗时/性能有极端要求的场景下，必须考虑到网络虚拟化带来的时延折损，以及各种各样原因带来的成功率下降问题（超时，丢包等等等），在现有生产环境上的业务模块都选择这种方式唯独最底层的索引引擎没有用。
弹性网卡在不同云厂商不同机型配置有所区别，屏蔽这些区别在配置和维护方面有额外成本。最方便的还是在代码层面能够做到屏蔽这些硬件层面的差异。举个例子，启动的HA3实例可以按48核为基本单位，在96核与102核的机型上开启2实例，在256核机器上开启4实例。不开启SO_REUSEPORT时，需要维护机器和端口的关系（当前的命名服务对同一个服务多端口不友好），结合多云，几十个分片，数百台服务器的场景，这个配置管理成本较高。开启SO_REUSEPORT，单机不同实例QRS共用同样端口，对外屏蔽了单机不同实例的差异，不同机型区别仅剩权重，这些在负载均衡上都容易处理，在当前生产环境上使用效果较好，应用和管理成本都比较低。

**Comment by xuxijie** [comment]
了解了

**Comment by xuxijie** [comment]
经过考虑SO_REUSEPORT 这个功我们不会支持，因为开启了这个功能之后，请求会随机被上层的进程处理，正常请求没有问题，但是心跳请求会有异常，特别是发送target的时候，无法控制发送给哪个进程。
