### ISSUE TITLE
如何将日志打到标准输出

### ISSUE THREAD

**Issue by breeent** [alibaba/havenask#37]
目前部署平台采集日志的方式为采集标准输出的数据，所以需要把输出到ha3.log和access.log的内容打到标准输出，请问如何配置呢？目前尝试过修改ha3_install中的ha3_alog.conf，将FileAppender改为ConsoleAppender，但是没有效果。如果通过软链把ha3.log和access.log链接到标准输出，会在local_search_starter.py中卡在wait_load()里面，因为函数中tail ha3.log一直拿不到内容导致无限循环。

**Comment by xuxijie** [comment]
现在日志采集的是stdout 这个文件吗？

**Comment by breeent** [comment]
> 现在日志采集的是stdout 这个文件吗？

是的，现在问题的关键是进程启动后需要通过日志的某部分来判断就绪状态，如果这部分日志被采集走了，进程就无法进行后续的流程了

**Comment by xuxijie** [comment]
有其他办法可以不通过查看日志来确定searcher的状态，我确认下明天回复你。

**Comment by breeent** [comment]
> > > 现在日志采集的是stdout 这个文件吗？
> > 
> > 
> > 是的，现在问题的关键是进程启动后需要通过日志的某部分来判断就绪状态，如果这部分日志被采集走了，进程就无法进行后续的流程了
> 
> 脚本里面现在的逻辑是查ha3.log，得到结果之后在get_listen_ports方法中调用借助获取curl __method__查看HeartbeatService接口是否准备好 可以试试看去掉ha3.log这部分逻辑，直接循环get_listen_ports方法，HeartbeatService接口准备好就说明searcher启动的一阶段完成

嗯嗯把代码修改成下面这样可以把服务起起来，能修改一下ha3_dev镜像里面相关这部分的代码吗，不然操作起来不太方便
@@ -564,10 +564,19 @@
         f.write("%d %s\n" % (pid, rundir))
         f.close()
 
-        self.wait_load(rundir)
+        #self.wait_load(rundir)
+        time_count=60
+        while time_count>0:
         status, http_port, arpc_port = self.get_listen_ports(pid)
         if not status:
-            print 'get qrs listen port failed, pid [%d]' % pid
+                print "rest retry time:%d"%time_count
+                #print 'get qrs listen port failed, pid [%d]' % pid
+                #return False
+            else:
+                break
+            time_count-=1
+        if time_count<=0:
+            print "get qrs listen port failed, pid [%d]"%pid
             return False
         self.qrs_port_list = (int(http_port), int(arpc_port))
         with open(self.portFile, 'w') as portFile:

**Comment by breeent** [comment]
> > > 现在日志采集的是stdout 这个文件吗？
> > 
> > 
> > 是的，现在问题的关键是进程启动后需要通过日志的某部分来判断就绪状态，如果这部分日志被采集走了，进程就无法进行后续的流程了
> 
> 脚本里面现在的逻辑是查ha3.log，得到结果之后在get_listen_ports方法中调用借助获取curl __method__查看HeartbeatService接口是否准备好 可以试试看去掉ha3.log这部分逻辑，直接循环get_listen_ports方法，HeartbeatService接口准备好就说明searcher启动的一阶段完成

嗯嗯把代码改成下面这样是可以把服务起起来的，可以在ha3_dev镜像里面也修改一下这部分相关的代码吗，不然操作起来不太方便
~~~
@@ -564,10 +564,19 @@
         f.write("%d %s\n" % (pid, rundir))
         f.close()
 
-        self.wait_load(rundir)
+        #self.wait_load(rundir)
+        time_count=60
+        while time_count>0:
              status, http_port, arpc_port = self.get_listen_ports(pid)
              if not status:
-                 print 'get qrs listen port failed, pid [%d]' % pid
+                print "rest retry time:%d"%time_count
+                #print 'get qrs listen port failed, pid [%d]' % pid
+                #return False
+            else:
+                break
+            time_count-=1
+        if time_count<=0:
+            print "get qrs listen port failed, pid [%d]"%pid
              return False
         self.qrs_port_list = (int(http_port), int(arpc_port))
         with open(self.portFile, 'w') as portFile:
~~~

**Comment by dyuyang** [comment]
> > > > 现在日志采集的是stdout 这个文件吗？
> > > 
> > > 
> > > 是的，现在问题的关键是进程启动后需要通过日志的某部分来判断就绪状态，如果这部分日志被采集走了，进程就无法进行后续的流程了
> > 
> > 
> > 脚本里面现在的逻辑是查ha3.log，得到结果之后在get_listen_ports方法中调用借助获取curl __method__查看HeartbeatService接口是否准备好 可以试试看去掉ha3.log这部分逻辑，直接循环get_listen_ports方法，HeartbeatService接口准备好就说明searcher启动的一阶段完成
> 
> 嗯嗯把代码改成下面这样是可以把服务起起来的，可以在ha3_dev镜像里面也修改一下这部分相关的代码吗，不然操作起来不太方便
> 
> ```
> @@ -564,10 +564,19 @@
>          f.write("%d %s\n" % (pid, rundir))
>          f.close()
>  
> -        self.wait_load(rundir)
> +        #self.wait_load(rundir)
> +        time_count=60
> +        while time_count>0:
>               status, http_port, arpc_port = self.get_listen_ports(pid)
>               if not status:
> -                 print 'get qrs listen port failed, pid [%d]' % pid
> +                print "rest retry time:%d"%time_count
> +                #print 'get qrs listen port failed, pid [%d]' % pid
> +                #return False
> +            else:
> +                break
> +            time_count-=1
> +        if time_count<=0:
> +            print "get qrs listen port failed, pid [%d]"%pid
>               return False
>          self.qrs_port_list = (int(http_port), int(arpc_port))
>          with open(self.portFile, 'w') as portFile:
> ```

好的，我们近期把这个改了通知你

**Comment by breeent** [comment]
> > > > > 现在日志采集的是stdout 这个文件吗？
> > > > 
> > > > 
> > > > 是的，现在问题的关键是进程启动后需要通过日志的某部分来判断就绪状态，如果这部分日志被采集走了，进程就无法进行后续的流程了
> > > 
> > > 
> > > 脚本里面现在的逻辑是查ha3.log，得到结果之后在get_listen_ports方法中调用借助获取curl __method__查看HeartbeatService接口是否准备好 可以试试看去掉ha3.log这部分逻辑，直接循环get_listen_ports方法，HeartbeatService接口准备好就说明searcher启动的一阶段完成
> > 
> > 
> > 嗯嗯把代码改成下面这样是可以把服务起起来的，可以在ha3_dev镜像里面也修改一下这部分相关的代码吗，不然操作起来不太方便
> > ```
> > @@ -564,10 +564,19 @@
> >          f.write("%d %s\n" % (pid, rundir))
> >          f.close()
> >  
> > -        self.wait_load(rundir)
> > +        #self.wait_load(rundir)
> > +        time_count=60
> > +        while time_count>0:
> >               status, http_port, arpc_port = self.get_listen_ports(pid)
> >               if not status:
> > -                 print 'get qrs listen port failed, pid [%d]' % pid
> > +                print "rest retry time:%d"%time_count
> > +                #print 'get qrs listen port failed, pid [%d]' % pid
> > +                #return False
> > +            else:
> > +                break
> > +            time_count-=1
> > +        if time_count<=0:
> > +            print "get qrs listen port failed, pid [%d]"%pid
> >               return False
> >          self.qrs_port_list = (int(http_port), int(arpc_port))
> >          with open(self.portFile, 'w') as portFile:
> > ```
> 
> 好的，我们近期把这个改了通知你
嗯嗯感谢
