### ISSUE TITLE
依赖的镜像太大了本地基本玩不了

### ISSUE THREAD

**Issue by zhangkele1221** [alibaba/havenask#5]

**Comment by xuxijie** [comment]
开发镜像会有些大，有些ut依赖的库在里面。运行时镜像我们会进行裁剪，下个版本会小很多。

**Comment by maoxiajun** [comment]
有没有国内的镜像源，几个G的镜像小水管拉不下来

**Comment by xuxijie** [comment]
我们会提供一个阿里云的镜像源

**Comment by dyuyang** [comment]
> _No description provided._

如果是运行时镜像ha3_runtime，可以删掉老的重新pull一下试试看
重新发布了一个缩减过的镜像，镜像下载大小2G，容器启动后总大小8G

**Comment by dyuyang** [comment]
> 有没有国内的镜像源，几个G的镜像小水管拉不下来

可以看一下最新的README，添加了一个阿里云的镜像源

此外镜像下载大小从8G缩到了2G，容器启动后大小从20G缩减到了7G
