### ISSUE TITLE
Part of the real-time index code is incomplete

### ISSUE THREAD

**Issue by cnangel** [alibaba/havenask#51]
镜像版本havenask/ha3_runtime:0.3.0(336a1ca3e83f)二进制库无问题
其日志：
`[INFO] [631,build/release64/build_service/workflow/RawDocBuilderConsumer.cpp -- getLocator():83] [builder locator [0:-1]]
`
但代码对应不上。
无论是master分支还是其他分支，RawDocBuilderConsumer.cpp只有59行，且其编译出来的代码，无法通过实时索引验证。
看上去应该是索引parse&builder过程中缺少了 对RawDoc 的opType传递，导致出现
`unknown doc operator`的错误。

**Comment by WenyiDuan** [comment]
有个commit没合进来，已提交pr(#52 )

**Comment by cnangel** [comment]
Verified
