### ISSUE TITLE
create_container 失败

### ISSUE THREAD

**Issue by gavxin** [alibaba/havenask#6]
几个问题

1. master 上的 Latest commit [1098497] awf 是拼写错误么？
https://github.com/alibaba/havenask/blob/main/docker/create_container.sh#L116

2. 容器里的 /tmp/after_start.sh 跑失败，好像没有 /etc/init.d/sshd 这种路径，下面那个行好像也不对
https://github.com/alibaba/havenask/blob/main/docker/create_container.sh#L88

反正跑不起来……

**Comment by xuxijie** [comment]
应该是拼写错误。具体的报错可以贴一下吗？我们看下什么问题

**Comment by xuxijie** [comment]
是手动执行了after_start.sh这个脚本了吗？这个是不需要手动执行的，创建容器之后直接通过sshme登录进去。

**Comment by gavxin** [comment]
主要是自动执行后，sshme 登录不进去，所以找了找原因，感觉是 after_start.sh 执行出问题，所以手动执行看了下

**Comment by gavxin** [comment]
执行脚本后，显示 start container success
docker ps 可以看到已经在跑
sshme 尝试登录，会失败
docker exec 进容器看，sshd 根本没跑起来


如果手动执行 /tmp/after_start.sh 可以发现
```
./after_start.sh: line 3: docker: command not found
sed: can't read /etc/init.d/sshd: No such file or directory
sed: can't read /etc/rc.d/rc3.d/S*sshd: No such file or directory
```

**Comment by gavxin** [comment]
此外，希望在 sshme, stopContainer.sh 上加上 shebang 头，看着可执行但是直接运行不了

**Comment by xuxijie** [comment]
已经加上了shebang头，sshme报错可以贴一下吗？我怀疑是sshd或者是密钥的问题。可以看下home目录下是否有.ssh的目录，已经对应的id_rsa.pub这些文件，或者容器里面sshd进程是否正常。

**Comment by gavxin** [comment]
请参考上面回复内容……
> docker exec 进容器看，sshd 根本没跑起来

**Comment by dyuyang** [comment]
> 请参考上面回复内容……
> 
> > docker exec 进容器看，sshd 根本没跑起来

之前的脚本对于兼容性考虑不足，已经针对这个问题简化了脚本。现在的脚本不用复杂的ssh登陆机器，可以重新pull一下试试看。

**Comment by gavxin** [comment]
重新试了下，可以了
