### ISSUE TITLE
您好，请问在阿里云上面的文档中说的那些分词器后续有开放的计划吗？后续是否会有关于DSL、用户自行编写算分插件和排序插件等内容的文档呢？

### ISSUE THREAD

**Issue by breeent** [alibaba/havenask#8]

**Comment by dyuyang** [comment]
阿里云上内部使用的分词器不会开放，但是之后会开放基于开源的jieba分词模型的分词器，后续插件开发的文档也会补上

**Comment by breeent** [comment]
请问插件开发的文档大概什么时候可以发布呢

**Comment by breeent** [comment]
> 阿里云上内部使用的分词器不会开放，但是之后会开放基于开源的jieba分词模型的分词器，后续插件开发的文档也会补上

请问插件开发的文档大概什么时候可以发布呢

**Comment by dyuyang** [comment]
这个月底或者12月初会发布结巴分词、向量索引、插件开发文档等

**Comment by codingcai** [comment]
> 这个月底或者12月初会发布结巴分词、向量索引、插件开发文档等

请问autil基础库有预期啥时候发布吗？ 看代码很多代码引用了此基础库的代码。谢谢

**Comment by dyuyang** [comment]
> > 这个月底或者12月初会发布结巴分词、向量索引、插件开发文档等
> 
> 请问autil基础库有预期啥时候发布吗？ 看代码很多代码引用了此基础库的代码。谢谢

https://github.com/alibaba/havenask/issues/9
autil估计要等到下个1.0版本开放，目前没有明确时间，应该是明年
