### ISSUE TITLE
请问下havenask是依赖了非开源的库吗，比如 include “suez/turing” 目录下的代码

### ISSUE THREAD

**Issue by peitao** [alibaba/havenask#81]
请问下havenask是依赖了非开源的库吗，比如 include “suez/turing” 目录下的代码

**Comment by xuxijie** [comment]
是的，havenask目前正在将内部的代码不断的整理对外开源，这个需要一个过程。最近我们会发一个版本里面会开放更多的代码，敬请关注。

**Comment by peitao** [comment]
多谢，关注中，close了
