### ISSUE TITLE
通过kvpair传参，转换provider结果为空指针

### ISSUE THREAD

**Issue by taomengen** [alibaba/havenask#84]
使用方式：
通过sql的kvpair传递参数，然后在evaluate中使用，格式如下：
&&kvpair=start_time:2023-06-01 10:00:00 000;end_time:2023-06-03 10:00:00 000

获取参数思路：
在udf_plugins的函数beginRequest中解析出 _resource，然后通过_resource解析出kvpairs

问题：在转换beginRequest函数参数provider时，转换出的结果是空指针，导致无法继续解析出_resource

代码：

```
bool SumFuncInterface::beginRequest(suez::turing::FunctionProvider *provider) {
    // 根据日志，provider不为NULL
    if (provider == NULL) {
        HA3_LOG(INFO, "provider is NULL in beginRequest");
        return true;
    }
    
    HA3_NS(func_expression)::FunctionProvider *funcProvider = 
        dynamic_cast<HA3_NS(func_expression)::FunctionProvider *>(provider); 

    // 根据日志，funcProvider为NULL
    if (funcProvider == NULL) {
        HA3_LOG(INFO, "funcProvider is NULL in beginRequest");
        return true;
    }

    auto resource = funcProvider->getSearchPluginResource();


    // 获取kvpairs代码
    // ...

    return true;
}
```

**Comment by lixuefeng123** [comment]
sql udf插件不支持从kvpair里面获取参数，可以将参数作为udf的参数传递，通过FunctionSubExprVec获取udf中的参数。
![image](https://github.com/alibaba/havenask/assets/9464805/dcc748bb-8813-46f8-bfff-8b967dfc94e8)
