### ISSUE TITLE
请教一个online IndexBuilder 使用问题，为什么代码会删除rt_index_partition

### ISSUE THREAD

**Issue by peitao** [alibaba/havenask#99]
问题在119行，谢谢
![WX20230621-205950](https://github.com/alibaba/havenask/assets/3378117/5e3006dc-19c5-48ee-9607-8779bd082e45)

**Comment by xuxijie** [comment]
这个是哪部分的代码？具体文件路径麻烦贴一下

**Comment by peitao** [comment]
这是我自己写的一段测试的代码

**Comment by xuxijie** [comment]
删除rt这部分代码是从哪边搞的？你自己写的？
